---

 - name: Manage AWS S3 
   s3:
     aws_access_key: "{{ item.aws_access_key | default(omit) }}"
     aws_secret_key: "{{ item.aws_secret_key | default(omit) }}"
     bucket: "{{ item.bucket | default(omit) }}"
     dest: "{{ item.dest | default(omit) }}"
     ec2_url: "{{ item.ec2_url | default(omit) }}"
     encrypt: "{{ item.encrypt | default(omit) }}"
     expiration: "{{ item.expiration | default(omit) }}"
     headers: "{{ item.headers | default(omit) }}"
     marker: "{{ item.marker | default(omit) }}"
     max_keys: "{{ item.max_keys | default(omit) }}"
     metadata: "{{ item.metadata | default(omit) }}"
     mode: "{{ item.mode | default(omit) }}"
     object: "{{ item.object | default(omit) }}"
     overwrite: "{{ item.overwrite | default(omit) }}"
     permission: "{{ item.permission | default(omit) }}"
     prefix: "{{ item.prefix | default(omit) }}"
     profile: "{{ item.profile | default(omit) }}"
     region: "{{ item.region | default(omit) }}"
     retries: "{{ item.retries | default(omit) }}"
     s3_url:  "{{ item.s3_url | default(omit) }}"
     security_token: "{{ item.security_token | default(omit) }}"
     src: "{{ item.src | default(omit) }}"
     validate_certs: "{{ item.validate_certs | default(omit) }}"
     version:  "{{ item.version | default(omit) }}"
   with_items: "{{ aws_s3 | mandatory }}"